print('hi how are you today?')
print('what is your name?')
name = input()
print('Hi, ' + name)
print('How was your day, ' + name + '?')
day = input()
print(day + ', huh?')
print('what did you do today?')
stuff = input()
print('so you ' + stuff + '?')
input()
